pipeline 
{
agent {
  label 'Devserver'
}
tools {
  maven 'maven'
}

stages {

    stage('build')
    {
        steps
        {
            sh "mvn clean package"
        }
        post {
        success {
        // One or more steps need to be included within each condition's block.
            archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
                }
        }


    }
        stage('test ')
    {
        steps
        {
            sh 'echo test'
        }

    }
        stage('deploy')
    {
        steps
        {
            sh 'echo deploy'
        }

    }
}



}