pipeline 
{
agent {
  label 'Devserver'
}
// parameters {
//   string defaultValue: 'gopal', name: 'Lastname'
parameters {
  choice choices: ['dev', 'prod'], name: 'select_env'
}

}
environment {
    NAME = "mathan"
}

tools {
  maven 'maven'
}

stages {

    stage('build')
    {
        steps
        {
            sh "mvn clean package -DskipTests=true"
            sh "echo $NAME ${params.Lastname}"
        }
        post {
        success {
        // One or more steps need to be included within each condition's block.
            archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
                }
        }


    }
    stage('test ')
    {
        parallel {
            stage('test a')
            {
                steps
                {
                    echo "test A"
                }
            }
            stage('test b')
            {
                steps
                {
                    echo "test B"
                }
            }
        }
        post 
        {
        success 
        {
            // One or more steps need to be included within each condition's block.
            archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
                }
        }

    }
        stage('deploy')
    {
        steps
        {
            sh 'echo deploy'
        }

    }
}



}
